format_strawberryfield.iiif_settings:
  type: config_object
  label: 'Archipelago IIIF Server configurations'
  mapping:
    pub_server_url:
      type: string
      label: 'Public IIIF server URL'
    int_server_url:
      type: string
      label: 'Internal IIIF server URL'
# this definition is used internally so as not to repeat
strawberryfield_formatter_base:
  type: mapping
  label: 'Base configurations for Strawberryfield formatters'
  mapping:
    iiif_base_url:
      type: format_strawberryfield.iiif_settings.pub_server_url
    iiif_base_url_internal:
      type: format_strawberryfield.iiif_settings.int_server_url
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: integer
    max_height:
      type: integer
    use_iiif_globals:
      type: boolean
      label: 'Whether to use global IIIF settings or not.'
# individual formatters:
field.formatter.settings.strawberry_3d_formatter:
  type: strawberryfield_formatter_base
  label: 'FORMATTER Config for strawberry_3d_formatter'
  mapping:
    number_models:
      type: integer
field.formatter.settings.strawberry_audio_formatter:
  type: strawberryfield_formatter_base
  label: 'FORMATTER Config for strawberry_audio_formatter'
  mapping:
    audio_type:
      type: string
    number_media:
      type: integer
field.formatter.settings.strawberry_image_formatter:
  type: strawberryfield_formatter_base
  label: 'FORMATTER Config for strawberry_image_formatter'
  mapping:
    number_images:
      type: integer
    quality:
      type: string
    rotation:
      type: string
field.formatter.settings.strawberry_media_formatter:
  type: strawberryfield_formatter_base
  label: 'FORMATTER Config for strawberry_media_formatter'
  mapping:
    iiif_group:
      type: boolean
      label: 'Whether multiple media sources should use a single IIIF viewer or not.'
    thumbnails:
      type: boolean
# note: strawberry_metadata_formatter is not using the base like the others.
field.formatter.settings.strawberry_metadata_formatter:
  type: mapping
  label: 'FORMATTER Config for strawberry_metadata_formatter using Twig'
  mapping:
    label:
      type: string
    specs:
      type: url
    metadatadisplayentity_id:
      type: string
    metadatadisplayentity_uselabel:
      type: boolean
field.formatter.settings.strawberry_paged_formatter:
  type: strawberryfield_formatter_base
  label: 'FORMATTER Config for strawberry_paged_formatter'
  mapping:
    type: boolean
    label: 'Whether multiple media sources should use a single IIIF viewer or not.'
  mediasource:
    type: string
  metadatadisplayentity_source:
    type: string
  manifesturl_source:
    type: string
field.formatter.settings.strawberry_pannellum_formatter:
  type: strawberryfield_formatter_base
  label: 'FORMATTER Config for strawberry_pannellum_formatter'
  mapping:
    hotSpotDebug:
      type: boolean
    image_type:
      type: string
    json_key_hotspots:
      type: string
    panorama_type:
      type: integer
    quality:
      type: string
    rotation:
      type: string
field.formatter.settings.strawberry_video_formatter:
  type: strawberryfield_formatter_base
  label: 'FORMATTER Config for strawberry_video_formatter'
  mapping:
    audio_type:
      type: string
    json_key_source_for_poster:
      type: string
    number_media:
      type: integer
    posterframe:
      type: string